apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: xxx/grpc-server:0.0.1
          ports:
            - containerPort: 8001