version: '3.9'

services:
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
  server1:
    build:
      context: .
      dockerfile: server.Dockerfile
  server2:
    build:
      context: .
      dockerfile: server.Dockerfile
#  client:
#    build:
#      context: .
#      dockerfile: client.Dockerfile
#    ports:
#      - "9001:9001"
